Fix find LdapTemplate, specifying return attributes.
spring-projects/spring-ldap pull request #569
Opened 2021-02-04 16:58 UTC by orlandosso

LdapQuery allows the user to define ToReturn attributes, but does not respect the attributes defined.

```java
String [] atributtes = new String [] {"cn", "name", "email"};

var queryLdap = LdapQueryBuilder.query ()
        .attributes (attributtes)
        .base ("ou = company, o = department")
        . where ("cn"). is ("123456");

var user = ldapTemplate.findOne(queryLdap, UserEntity.class);

```

The attributes are just ignored, and overwritten by following code.

```java
String[] attributes = this.odm.manageClass(clazz);
searchControls.setReturningAttributes(attributes);
```

The correction involves verifying that the attributes for return have been informed.

```java
if (isCustomReturningAttributes(searchControls)) {
            String[] attributes = this.odm.manageClass(clazz);
            searchControls.setReturningAttributes(attributes);
}
```

2021-02-05 16:13 UTC, rwinch commented
Thanks for the PR. Can you please add test(s) to the PR?

2021-02-05 16:14 UTC, rwinch requested changes
Please add tests

2022-01-19 17:20 UTC, jzheaux commented
Hi, @orlandosso, thanks for your contribute.

Are you able to address Rob's feedback? I can help sort things out, if not. If I haven't heard from you in a week or so, I'll apply the described changes myself.

2022-01-19 17:20 UTC, pivotal-cla commented
@orlandosso Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-ldap&pullRequestId=569)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-ldap&pullRequestId=569) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2022-02-01 21:08 UTC, jzheaux commented
This is now merged into `2.4.x` with df40b394653e84de4fb846634bf0040799397e79 and a polish of 255bfaabcbf6375a9f9848ecbfee0fd94b094934.

Note that the polish changes the behavior so that returning attributes are only populated if the value is initially `null` instead of if it is `null` or empty.

This is also now merged into `main`.

2022-02-01 21:08 UTC, closed without merging